# Environment Settings
gpu_id: 1

# Model Settings
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.2
hidden_act: gelu
layer_norm_eps: 1.e-12
initializer_range: 0.02
loss_type: CE  # ['CE', 'BPR']

similarity_type: dot
cl_loss_type: infonce  # ['dcl', 'infonce']
cl_lambda: 0.1
scl_lambda: 0.0
tau: 1  # softmax
gumbel_tau: 100
alpha: 0.2
eta: 0.8   # crop
gamma: 0.4   # mask
beta: 0.3  # reorder
update_freq: 3
policy_trm_num_layers: 2
pc_lr: 1e-5
pc_epochs: 3
ad_atk: True 
consider_su_aug: False
aug_domain: ALL # ['CL4Rec', 'CL4Rec+SU', 'SU+RSU', 'ALL']
start_policy_controll_epoch: 3
randomness: 10
# Data settings
MAX_ITEM_LIST_LENGTH: 8

# Training Settings
train_batch_size: 256
neg_sampling: null
view_difficulty: 10.0
