# Environment Settings
gpu_id: 3

# Model Settings
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.4
attn_dropout_prob: 0.4
hidden_act: gelu
layer_norm_eps: 1.e-12
initializer_range: 0.01
loss_type: CE  # ['CE', 'BPR']
learning_rate: 0.001
similarity_type: dot
cl_loss_type: infonce  # ['dcl', 'infonce']
cl_lambda: 0.1
sl_lambda: 0.1
scl_lambda: 0.2
aug_type1: random # ['crop', 'mask', 'reorder', 'random']
aug_type2: retrieval
tau: 1  # softmax
eta: 0.2   # crop
gamma: 0.2   # mask
beta: 0.2   # reorder
start_ecl_epoch: 3
hard_sample: 1
update_freq: 8

# Data settings
MAX_ITEM_LIST_LENGTH: 20

# Training Settings
train_batch_size: 256
neg_sampling: null