# Environment Settings
gpu_id: 0

# Model Settings
embedding_size: 64
hidden_size: 128
num_layers: 1
dropout_prob: 0.3
loss_type: 'CE'

# Data settings
MAX_ITEM_LIST_LENGTH: 5

# Training Settings
train_batch_size: 512
neg_sampling: null
