# Environment Settings
gpu_id: 0

# Model Settings
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.1
attn_dropout_prob: 0.1
hidden_act: gelu
layer_norm_eps: 1.e-12
initializer_range: 0.02
loss_type: CE  # ['CE', 'BPR']
aug_type1: random  # ['random', 'crop', 'mask', 'reorder']
aug_type2: random

sim: 'dot' # choose from {dot, cos}
tau: 1
lmd: 0.0
alpha: 0.01 # beta in paper
eta: 0.5 # crop
gamma: 0.5 # mask
beta: 0.8 # reorder
use_rl: 1
joint: 0

# Data settings

MAX_ITEM_LIST_LENGTH: 50
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list

# Training Settings
train_batch_size: 256
