# Environment Settings
gpu_id: 1

# Model Settings
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
item_attribute: 'class'
mask_ratio: 0.2
aap_weight: 0.3
mip_weight: 0.2
map_weight: 0.2
sp_weight: 0.1
# train_stage: 'pretrain'
pretrain_epochs: 100
save_step: 10
# pre_model_path: 'saved'
loss_type: 'CE'


# Data settings
MAX_ITEM_LIST_LENGTH: 5

# Training Settings
train_batch_size: 512
neg_sampling: null
