# Environment Settings
gpu_id: 0

# Model Settings
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: gelu
layer_norm_eps: 1.e-12
initializer_range: 0.01
loss_type: CE
learning_rate: 0.001

# Data settings
MAX_ITEM_LIST_LENGTH: 50

# Training Settings
train_batch_size: 128
neg_sampling: null