load_col:
  inter: [user_id, item_id, rating, timestamp]
  # item: [item_id, movie_title, release_year, genre] # for ml-1m
item_attribute: 'genre' # for s3rec usage
selected_features: ['genre'] # for FDSA usage
user_inter_num_interval: '[10,inf)'
item_inter_num_interval: '[10,inf)'
shuffle: False
