USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: stars
TIME_FIELD: timestamp
user_inter_num_interval: '[10,inf)'
item_inter_num_interval: '[10,inf)'
shuffle: False
load_col:
  inter: [user_id, item_id, stars, timestamp]